### PR TITLE
Fix repository URL

### PR DESCRIPTION
**Pull request by ivankravets**

### CODE REVIEW

**Comment by ivankravets** [comment]
P.S: Where is the source code of a library? Please fix symlink here https://github.com/medovarsky/PlatformIO-BearSSL

**Comment by medovarsky** [comment]
The library source is external, as I tried to give credits to the
library author and avoid pushing/pulling new releases from the upstream
to my clone. External repo is specified here:
https://github.com/medovarsky/PlatformIO-BearSSL/blob/master/.gitmodules

As far as I can see from EllipticCurve lib,
http://platformio.org/lib/show/321/EllipticCurve
https://github.com/kieransimkin/elliptic-platformio
pio should be able to fetch the submodules.

If this does not work, then I could clone the original libs,
but this is another element in the chain to break.

Ideas?


Thanks for the great work.

Lubos

**Comment by medovarsky** [comment]
merged to master branch

**Comment by ivankravets** [comment]
Try to download a source code using GitHub link https://github.com/medovarsky/PlatformIO-BearSSL/archive/master.zip

Do you see source code? I don't.

**Comment by medovarsky** [comment]
Thank you for your feedback.

That is right, the sources are not present when downloaded, but this is the same as the library mentioned above, https://github.com/kieransimkin/elliptic-platformio, where master.zip also does not contain the sources in the submodule, but when managed by Platformio, its sources are updated correctly because Platformio's git clone also updates the submodules. I think this is exactly the same case, it's just that my upstream is not on github, therefore github does not link the submodule in web UI automatically.

Sorry for the inconvenience. If this does not look good, I will send the patches to the original author, or fork the upstream, whichever will work. Any suggestion is welcome.

By the way, is there a way to debug a new library's json before registering the lib? I couldn't find any reference to this. Otherwise I would test my lib wrapper beforehand.

**Comment by medovarsky** [comment]
Btw, you can run git submodule init+update after cloning:
```
git clone git@github.com:medovarsky/PlatformIO-BearSSL.git
Cloning into 'PlatformIO-BearSSL'...
...
$ cd PlatformIO-BearSSL
$ ls -l BearSSL/
...
$ git submodule init
Submodule 'BearSSL' (https://www.bearssl.org/git/BearSSL) registered for path 'BearSSL'
$ git submodule update
Cloning into 'BearSSL'...
...
$ ls -l BearSSL/
...
```
Tried this with both EllipticCurve and this repo, and the submodule sources are cloned as expected.

**Comment by ivankravets** [comment]
> That is right, the sources are not present when downloaded, but this is the same as the library mentioned above, https://github.com/kieransimkin/elliptic-platformio

As a result, this library is empty: http://platformio.org/lib/show/321/EllipticCurve/installation

> Btw, you can run git submodule init+update after cloning

This is am issue of our API :( It manages GitHub repos using archives :( You can fill an issue here https://github.com/platformio/platformio-api/issues

**Pull request merged**
